### ISSUE TITLE
Enemy continue moving while game is paused

### ISSUE THREAD

**Issue by ping19** [The-Dream-Team/Tardis#143]

**Comment by dreamteam69** [comment]
Setting move speed to 0 should fix this, however could be problematic when resuming at later levels whereby the speed has already increased

**Comment by dreamteam69** [comment]
Just tried doing this, setting dy to 0 pauses the entities and upon returning to game, they start off from their last position.
However! There is a bug where the ship moves downwards at the start.

**Comment by ping19** [comment]
Have this been tested properly for atleast 3 seconds? setting dy to 0 alone will stop the entities moving, but it doesnt make any updates on the repositioning of the entities.

**Comment by dreamteam69** [comment]
I had set dy to 0 from within the pauseGame method.
dy had to be set as static within Entity (recommended by Eclipse)

**Comment by ping19** [comment]
I left dy as non static as we need it to be at different speed over time as levels changes, but i have fixed this issue with the entities so i will close this bug, feel free to check it and change things around if you find any problems or let me know.
