### ISSUE TITLE
Lives getting reduced automatically for no reasons

### ISSUE THREAD

**Issue by ping19** [The-Dream-Team/Tardis#173]

**Comment by dreamteam69** [comment]
First attempt to fix: 36cff3edb10969d9080770376c7ed97fe56ff508

Confirm status?

**Comment by ping19** [comment]
Problem still remains

**Comment by dreamteam69** [comment]
Attach log files to this issue for further inspection.

**Comment by dreamteam69** [comment]
Seems to be a 1/15 chance now when I have attempted it.

**Comment by dreamteam69** [comment]
Confirmed as enemy entities colliding, causing a false report of the ship hitting an enemy.

**Comment by dreamteam69** [comment]
Each entity is assigned a number
