### ISSUE TITLE
Change time to distance? (Cosmetic)

### ISSUE THREAD

**Issue by dreamteam69** [The-Dream-Team/Tardis#286]
Should time be renamed to metres to give the illusion of distance travelled?
This is similar to Temple Run

**Comment by ping19** [comment]
I like the idea! Will work on it after handing in our pre-planning docs, so we can show the changes of what we have planned for the future

**Comment by katiewood** [comment]
This wouldnt be practical for our game, because the game speeds up as the levels progress and so the distance would be inaccurate compared to using time.
